In [1]:
import pandas as pd

In [2]:
# Load the two raw files we need
games = pd.read_csv("../data/raw/games.csv")
clubs = pd.read_csv("../data/raw/clubs.csv")

In [3]:
print(games.shape)

(88958, 23)

In [4]:
print(clubs.shape)

(796, 17)

In [5]:
games.head()

,game_id,competition_id,season,round,date,home_club_id,away_club_id,home_club_goals,away_club_goals,home_club_position,...,stadium,attendance,referee,url,home_club_formation,away_club_formation,home_club_name,away_club_name,aggregate,competition_type
0,1026846,FIWC,2009,Round of 16,2010-06-26,3449,3589,2,1,NaN,...,Nelson Mandela Bay Stadium,30597.0,Wolfgang Stark,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,Uruguay,South Korea,2:1,national_team_competition
1,1026847,FIWC,2009,Round of 16,2010-06-27,3437,6303,3,1,NaN,...,FNB-Stadium,84377.0,Roberto Rosetti,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,Argentina,Mexico,3:1,national_team_competition
2,1027001,FIWC,2009,Round of 16,2010-06-26,3505,3441,1,2,NaN,...,Royal Bafokeng Stadium,34976.0,Viktor Kassai,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,United States,Ghana,1:2,national_team_competition
3,1027002,FIWC,2009,Round of 16,2010-06-27,3262,3299,4,1,NaN,...,Free State Stadium,40510.0,Jorge Larrionda,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,Germany,England,4:1,national_team_competition
4,1027048,FIWC,2009,Round of 16,2010-06-28,3379,3503,2,1,NaN,...,Moses Mabhida Stadion,61962.0,Undiano Mallenco,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,Netherlands,Slovakia,2:1,national_team_competition

In [8]:
games.tail()

,game_id,competition_id,season,round,date,home_club_id,away_club_id,home_club_goals,away_club_goals,home_club_position,...,stadium,attendance,referee,url,home_club_formation,away_club_formation,home_club_name,away_club_name,aggregate,competition_type
88953,986818,FIWC,2009,Group F,2010-06-24,3581,9171,0,0,NaN,...,Peter Mokaba Stadion,34850.0,Yuichi Nishimura,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,Paraguay,New Zealand,0:0,national_team_competition
88954,986819,FIWC,2009,Group G,2010-06-25,3300,3439,0,0,NaN,...,Moses Mabhida Stadion,62712.0,Armando Archundia Téllez,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,Portugal,Brazil,0:0,national_team_competition
88955,986820,FIWC,2009,Group G,2010-06-25,15457,3591,0,3,NaN,...,Mbombela Stadium,34763.0,Undiano Mallenco,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,North Korea,Ivory Coast,0:3,national_team_competition
88956,986821,FIWC,2009,Group H,2010-06-25,3700,3375,1,2,NaN,...,Loftus Versfeld Stadium,41958.0,Marco Rodríguez,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,Chile,Spain,1:2,national_team_competition
88957,986822,FIWC,2009,Group H,2010-06-25,3384,3590,0,0,NaN,...,Free State Stadium,28042.0,Héctor Baldassi,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,Switzerland,Honduras,0:0,national_team_competition

In [6]:
clubs.head()

,club_id,club_code,name,domestic_competition_id,total_market_value,squad_size,average_age,foreigners_number,foreigners_percentage,national_team_players,stadium_name,stadium_seats,net_transfer_record,coach_name,last_season,filename,url
0,10,arminia-bielefeld,Arminia Bielefeld,L1,NaN,27,25.3,15,55.6,4,SchücoArena,26515,+€5.90m,NaN,2021,../data/raw/transfermarkt-scraper/2021/clubs.j...,https://www.transfermarkt.co.uk/arminia-bielef...
1,10004,paris-fc,Paris FC,FR1,NaN,27,27.2,14,51.9,7,Stade Jean Bouin,19904,€-25.00m,Stéphane Gilli,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/paris-fc/start...
2,10010,esporte-clube-bahia,Esporte Clube Bahia,BRA1,NaN,32,26.6,9,28.1,3,Arena Fonte Nova,47364,+€8.14m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/esporte-clube-...
3,1003,leicester-city,Leicester City,GB1,NaN,29,25.9,17,58.6,9,King Power Stadium,32259,+€57.30m,Steve Cooper,2024,../data/raw/transfermarkt-scraper/2024/clubs.j...,https://www.transfermarkt.co.uk/leicester-city...
4,1005,us-lecce,US Lecce,IT1,NaN,39,23.8,36,92.3,10,Ettore Giardiniero,31559,+€3.35m,Eusebio Di Francesco,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/us-lecce/start...

In [7]:
games.info()

<class 'pandas.DataFrame'>
RangeIndex: 88958 entries, 0 to 88957
Data columns (total 23 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   game_id                 88958 non-null  int64
 1   competition_id          88958 non-null  str
 2   season                  88958 non-null  int64
 3   round                   88958 non-null  str
 4   date                    88958 non-null  str
 5   home_club_id            88958 non-null  int64
 6   away_club_id            88958 non-null  int64
 7   home_club_goals         88958 non-null  int64
 8   away_club_goals         88958 non-null  int64
 9   home_club_position      63581 non-null  float64
 10  away_club_position      63581 non-null  float64
 11  home_club_manager_name  88114 non-null  str
 12  away_club_manager_name  88114 non-null  str
 13  stadium                 88716 non-null  str
 14  attendance              78155 non-null  float64
 15  referee                 88280 non-null  str
 16  url                     88958 non-null  str
 17  home_club_formation     80758 non-null  str
 18  away_club_formation     80885 non-null  str
 19  home_club_name          88872 non-null  str
 20  away_club_name          88922 non-null  str
 21  aggregate               88958 non-null  str
 22  competition_type        87744 non-null  str
dtypes: float64(3), int64(6), str(14)
memory usage: 35.4 MB